services:
  # A Docker web service
  - type: web
    name: flask-hello-world
    runtime: python
    plan: free
    region: singapore
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app